import os
import datetime
from pathlib import Path
import sys
import json
import yaml
import logging
import logging.config
from typing import Union, Optional

from print_colored_text import bcolors

logger = logging.getLogger("__main__." + __name__)


def create_gallery_results_dict(repeat_ids: list, blacklist: list) -> dict:

    gallery_results = {
        "finished": [],
        "already_downloaded": [],
        "repeats": repeat_ids,
        "blacklists": blacklist,
        "updated_tags": [],
        "initial_fails": [],
        "retry_fails": [],
    }
    return gallery_results


def print_start_message(download_dir) -> None:

    message = (
        f"\n{bcolors.HEADER}NHENTAI SCRAPER{bcolors.ENDC}\n\n"
        f"Downloading to: {download_dir}\n"
    )

    print('\u2500'*get_separation_line_width())
    print(message)
    print('\u2500'*get_separation_line_width())


def get_application_folder_dir(_internal: bool= False) -> str:
    # Returns the folder directory containting the application/program

    # when running executable generated by pyinstaller
    if getattr(sys, "frozen", False):
        if _internal:
            # https://stackoverflow.com/questions/53587322/
            # how-do-i-include-files-with-pyinstaller
            return sys._MEIPASS
        else:
            return os.path.dirname(sys.executable)
    # when running python script (placed inside ./src/)
    elif __file__:
        return os.path.abspath(
            f"{os.path.dirname(__file__)}/.."
        )
    else:
        return os.path.abspath(f"{os.getcwd()}/..")


def set_download_dir(download_dir: Optional[Union[str, Path]] = None) -> Path:

    application_folder_path = get_application_folder_dir()
    if download_dir is None:
        download_dir = Path(application_folder_path) / "Downloaded"
    if not Path(download_dir).is_absolute():
        download_dir = Path(application_folder_path) / download_dir
    download_dir = Path(download_dir).absolute()

    if not download_dir.is_dir():
        download_dir.mkdir()

    return download_dir


def set_logging_config(
    logging_config_filename: Optional[Union[str, Path]] = None,
) -> None:

    application_folder_path = get_application_folder_dir(_internal=True)
    logging_dir = Path(application_folder_path) / "logs/"
    if not logging_dir.exists():
        logging_dir.mkdir()
    if logging_config_filename is None:
        logging_config_filename = logging_dir / "logging_config.yaml"

    logging_config_filename = Path(logging_config_filename)
    with open(logging_config_filename) as f:
        if logging_config_filename.suffix == ".yaml":
            logging_config = yaml.full_load(f)
        elif logging_config_filename.suffix == ".json":
            logging_config = json.load(f)

    logging_filename = os.path.join(
        logging_dir, f"{str(datetime.date.today())}.log"
    )
    logging_config["handlers"]["file"]["filename"] = logging_filename
    logging.config.dictConfig(logging_config)


def get_separation_line_width() -> int:

    try:
        # for running in terminal
        width = os.get_terminal_size().columns
    except OSError:
        # for running outside of a terminal (ex: cronjob)
        width = 80

    return width
